import { Schema, model } from "mongoose";
import { Series, Game } from "../models";

const series = {
    blg_vs_t1: {
        seriesId: "blgvst1",
        tournamentName: "Worlds 2024",
        date: new Date("2024-11-02"),
        teamOne: "BLG",
        teamTwo: "T1",
        games: [
            {
                gameId: "blgvst1_1",
                seriesId: "blgvst1",
                blueTeam: "T1",
                redTeam: "BLG",
                bluePickBans: {
                    banOne: "Jax",
                    banTwo: "Aurora",
                    banThree: "Vi",
                    banFour: "Kaisa",
                    banFive: "Kalista",
                    pickOne: "Varus",
                    pickTwo: "Yone",
                    pickThree: "Ashe",
                    pickFour: "Skarner",
                    pickFive: "Gnar",
                },
                redPickBans: {
                    banOne: "Sejuani",
                    banTwo: "Sylas",
                    banThree: "Ziggs",
                    banFour: "Renata",
                    banFive: "Jhin",
                    pickOne: "Rakan",
                    pickTwo: "Rumble",
                    pickThree: "Caitlyn",
                    pickFour: "Braum",
                    pickFive: "Rell",
                },
                blueWin: false,
                blueFirstBlood: false,
                blueFirstTower: false,
                blueObjectives: {
                    towers: 5,
                    topPlates: 1,
                    midPlates: 3,
                    botPlates: 3,
                    grubs: 2,
                    herald: 0,
                    barons: 0,
                    firstDrake: "Chemtech",
                    secondDrake: "",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                redObjectives: {
                    towers: 11,
                    topPlates: 4,
                    midPlates: 1,
                    botPlates: 3,
                    grubs: 4,
                    herald: 1,
                    barons: 1,
                    firstDrake: "Hextech",
                    secondDrake: "Hextech",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                duration: 1629,
            },
            {
                gameId: "blgvst1_2",
                seriesId: "blgvst1",
                blueTeam: "T1",
                redTeam: "BLG",
                bluePickBans: {
                    banOne: "Jax",
                    banTwo: "Aurora",
                    banThree: "Vi",
                    banFour: "Kaisa",
                    banFive: "Kalista",
                    pickOne: "Varus",
                    pickTwo: "Yone",
                    pickThree: "Ashe",
                    pickFour: "Skarner",
                    pickFive: "Gnar",
                },
                redPickBans: {
                    banOne: "Sejuani",
                    banTwo: "Sylas",
                    banThree: "Ziggs",
                    banFour: "Renata",
                    banFive: "Jhin",
                    pickOne: "Rakan",
                    pickTwo: "Rumble",
                    pickThree: "Caitlyn",
                    pickFour: "Braum",
                    pickFive: "Rell",
                },
                blueWin: false,
                blueFirstBlood: false,
                blueFirstTower: false,
                blueObjectives: {
                    towers: 5,
                    topPlates: 1,
                    midPlates: 3,
                    botPlates: 3,
                    grubs: 2,
                    herald: 0,
                    barons: 0,
                    firstDrake: "Chemtech",
                    secondDrake: "",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                redObjectives: {
                    towers: 11,
                    topPlates: 4,
                    midPlates: 1,
                    botPlates: 3,
                    grubs: 4,
                    herald: 1,
                    barons: 1,
                    firstDrake: "Hextech",
                    secondDrake: "Hextech",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                duration: 1645,
            },
            {
                gameId: "blgvst1_3",
                seriesId: "blgvst1",
                blueTeam: "BLG",
                redTeam: "T1",
                bluePickBans: {
                    banOne: "Jax",
                    banTwo: "Aurora",
                    banThree: "Vi",
                    banFour: "Kaisa",
                    banFive: "Kalista",
                    pickOne: "Varus",
                    pickTwo: "Yone",
                    pickThree: "Ashe",
                    pickFour: "Skarner",
                    pickFive: "Gnar",
                },
                redPickBans: {
                    banOne: "Sejuani",
                    banTwo: "Sylas",
                    banThree: "Ziggs",
                    banFour: "Renata",
                    banFive: "Jhin",
                    pickOne: "Rakan",
                    pickTwo: "Rumble",
                    pickThree: "Caitlyn",
                    pickFour: "Braum",
                    pickFive: "Rell",
                },
                blueWin: false,
                blueFirstBlood: false,
                blueFirstTower: false,
                blueObjectives: {
                    towers: 5,
                    topPlates: 1,
                    midPlates: 3,
                    botPlates: 3,
                    grubs: 2,
                    herald: 0,
                    barons: 0,
                    firstDrake: "Chemtech",
                    secondDrake: "",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                redObjectives: {
                    towers: 11,
                    topPlates: 4,
                    midPlates: 1,
                    botPlates: 3,
                    grubs: 4,
                    herald: 1,
                    barons: 1,
                    firstDrake: "Hextech",
                    secondDrake: "Hextech",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                duration: 1655,
            },
            {
                gameId: "blgvst1_4",
                seriesId: "blgvst1",
                blueTeam: "T1",
                redTeam: "BLG",
                bluePickBans: {
                    banOne: "Jax",
                    banTwo: "Aurora",
                    banThree: "Vi",
                    banFour: "Kaisa",
                    banFive: "Kalista",
                    pickOne: "Varus",
                    pickTwo: "Yone",
                    pickThree: "Ashe",
                    pickFour: "Skarner",
                    pickFive: "Gnar",
                },
                redPickBans: {
                    banOne: "Sejuani",
                    banTwo: "Sylas",
                    banThree: "Ziggs",
                    banFour: "Renata",
                    banFive: "Jhin",
                    pickOne: "Rakan",
                    pickTwo: "Rumble",
                    pickThree: "Caitlyn",
                    pickFour: "Braum",
                    pickFive: "Rell",
                },
                blueWin: false,
                blueFirstBlood: false,
                blueFirstTower: false,
                blueObjectives: {
                    towers: 5,
                    topPlates: 1,
                    midPlates: 3,
                    botPlates: 3,
                    grubs: 2,
                    herald: 0,
                    barons: 0,
                    firstDrake: "Chemtech",
                    secondDrake: "",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                redObjectives: {
                    towers: 11,
                    topPlates: 4,
                    midPlates: 1,
                    botPlates: 3,
                    grubs: 4,
                    herald: 1,
                    barons: 1,
                    firstDrake: "Hextech",
                    secondDrake: "Hextech",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                duration: 1902,
            },
            {
                gameId: "blgvst1_5",
                seriesId: "blgvst1",
                blueTeam: "BLG",
                redTeam: "T1",
                bluePickBans: {
                    banOne: "Jax",
                    banTwo: "Aurora",
                    banThree: "Vi",
                    banFour: "Kaisa",
                    banFive: "Kalista",
                    pickOne: "Varus",
                    pickTwo: "Yone",
                    pickThree: "Ashe",
                    pickFour: "Skarner",
                    pickFive: "Gnar",
                },
                redPickBans: {
                    banOne: "Sejuani",
                    banTwo: "Sylas",
                    banThree: "Ziggs",
                    banFour: "Renata",
                    banFive: "Jhin",
                    pickOne: "Rakan",
                    pickTwo: "Rumble",
                    pickThree: "Caitlyn",
                    pickFour: "Braum",
                    pickFive: "Rell",
                },
                blueWin: false,
                blueFirstBlood: false,
                blueFirstTower: false,
                blueObjectives: {
                    towers: 5,
                    topPlates: 1,
                    midPlates: 3,
                    botPlates: 3,
                    grubs: 2,
                    herald: 0,
                    barons: 0,
                    firstDrake: "Chemtech",
                    secondDrake: "",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                redObjectives: {
                    towers: 11,
                    topPlates: 4,
                    midPlates: 1,
                    botPlates: 3,
                    grubs: 4,
                    herald: 1,
                    barons: 1,
                    firstDrake: "Hextech",
                    secondDrake: "Hextech",
                    thirdDrake: "",
                    fourthDrake: "",
                    elderDrakes: 0,
                },
                duration: 1933,
            }
        ]
    }
}

// const GameSchema = new Schema<Game>(
//     {
//         gameId: { type: String, required: true, trim: true },
//         // seriesId: { type: String, required: true, trim: true },
//         blueTeam: { type: String, required: true, trim: true },
//         redTeam: { type: String, required: true, trim: true },
//         pickBans: {
//             // pickBanId: { type: String, required: true, trim: true },
//             // gameId: { type: String, required: true, trim: true },
//             blueBanOne: { type: String, required: true, trim: true },
//             blueBanTwo: { type: String, required: true, trim: true },
//             blueBanThree: { type: String, required: true, trim: true },
//             blueBanFour: { type: String, required: true, trim: true },
//             blueBanFive: { type: String, required: true, trim: true },
//             bluePickOne: { type: String, required: true, trim: true },
//             bluePickTwo: { type: String, required: true, trim: true },
//             bluePickThree: { type: String, required: true, trim: true },
//             bluePickFour: { type: String, required: true, trim: true },
//             bluePickFive: { type: String, required: true, trim: true },
//             redBanOne: { type: String, required: true, trim: true },
//             redBanTwo: { type: String, required: true, trim: true },
//             redBanThree: { type: String, required: true, trim: true },
//             redBanFour: { type: String, required: true, trim: true },
//             redBanFive: { type: String, required: true, trim: true },
//             redPickOne: { type: String, required: true, trim: true },
//             redPickTwo: { type: String, required: true, trim: true },
//             redPickThree: { type: String, required: true, trim: true },
//             redPickFour: { type: String, required: true, trim: true },
//             redPickFive: { type: String, required: true, trim: true },
//         },
//         blueWin: { type: Boolean, required: true, },
//         blueFirstBlood: { type: Boolean, required: true, },
//         blueFirstTower: { type: Boolean, required: true, },
//         blueTopPlates: { type: Number, required: true },
//         blueMidPlates: { type: Number, required: true },
//         blueBotPlates: { type: Number, required: true },
//         blueGrubs: { type: Number, required: true },
//         blueHerald: { type: Number, required: true },
//         blueBarons: { type: Number, required: true },
//         blueCloudDrakes: { type: Number, required: true },
//         blueOceanDrakes: { type: Number, required: true },
//         blueMountainDrakes: { type: Number, required: true },
//         blueInfernalDrakes: { type: Number, required: true },
//         blueHextechDrakes: { type: Number, required: true },
//         blueChemtechDrakes: { type: Number, required: true },
//         blueElderDrakes: { type: Number, required: true },
//         redTopPlates: { type: Number, required: true },
//         redMidPlates: { type: Number, required: true },
//         redBotPlates: { type: Number, required: true },
//         redGrubs: { type: Number, required: true },
//         redHerald: { type: Number, required: true },
//         redBarons: { type: Number, required: true },
//         redCloudDrakes: { type: Number, required: true },
//         redOceanDrakes: { type: Number, required: true },
//         redMountainDrakes: { type: Number, required: true },
//         redInfernalDrakes: { type: Number, required: true },
//         redHextechDrakes: { type: Number, required: true },
//         redChemtechDrakes: { type: Number, required: true },
//         redElderDrakes: { type: Number, required: true },
//     },
//     { collection: "games" }
// );

const SeriesSchema = new Schema<Series>(
    {
        seriesId: { type: String, required: true, trim: true },
        tournamentName: { type: String, required: true, trim: true },
        date: { type: Date, required: true, trim: true },
        teamOne: { type: String, required: true, trim: true },
        teamTwo: { type: String, required: true, trim: true },
        games: { type: new Array<Game>, required: true },
    },
    { collection: "series" }
);

const SeriesModel = model<Series>("Series", SeriesSchema);

function index(): Promise<Series[]> {
    return SeriesModel.find();
}

function get(seriesid: String): Promise<Series> {
    return SeriesModel.find({ seriesid })
        .then((list) => list[0])
        .catch((err) => {
            throw `${seriesid} Not Found`;
        });
}

export default { index, get };
export function getSeries(_: string) {
    return series["blg_vs_t1"];
}